// Generated by CoffeeScript 1.6.3
(function() {
  ({
    greedyAlgorithm: function(chars, validPixels) {
      var allShitty, char, checks, fits, i, j, keep, newChars, x, y, _i, _j, _k, _len, _ref, _ref1, _results;
      _results = [];
      while (chars.length > 0) {
        allShitty = true;
        newChars = [];
        for (_i = 0, _len = chars.length; _i < _len; _i++) {
          char = chars[_i];
          keep = true;
          x = char.offsetLeft;
          y = char.offsetTop;
          checks = [];
          checks[0] = [x, y];
          checks[1] = [x + char.width, y];
          checks[2] = [x, y + char.height];
          checks[3] = [x + char.width, y + char.height];
          fits = true;
          i = 0;
          if (char.attempts <= 3) {
            allShitty = false;
          }
          while (i < 4 - char.attempts) {
            i++;
            if (!(validPixels[i][0] && validPixels[i][1])) {
              fits = false;
            }
          }
          if (fits) {
            keep = false;
            for (i = _j = 0, _ref = char.width; 0 <= _ref ? _j <= _ref : _j >= _ref; i = 0 <= _ref ? ++_j : --_j) {
              for (j = _k = 0, _ref1 = char.width; 0 <= _ref1 ? _k <= _ref1 : _k >= _ref1; j = 0 <= _ref1 ? ++_k : --_k) {
                validPixels[i + x][j + y] = false;
              }
            }
          }
          if (keep) {
            newChars.add(char);
          }
        }
        if (!allShitty) {
          _results.push(chars = newChars);
        } else {
          _results.push(chars = []);
        }
      }
      return _results;
    }
  });

}).call(this);
