// Generated by CoffeeScript 1.6.3
(function() {
  var Particle;

  Particle = (function() {
    function Particle(elem) {
      this.elem = elem;
      this.style = elem.style;
      this.elem.style['zIndex'] = -9999;
      this.transformX = 0;
      this.transformY = 0;
      this.transformRotation = 0;
      this.offsetTop = window.getOffset(this.elem).top;
      this.offsetLeft = window.getOffset(this.elem).left;
      this.velocityX = 0;
      this.velocityY = 0;
    }

    return Particle;

  })();

  this.Particle = Particle;

}).call(this);
